/**
 * Stable, machine-readable error codes sent alongside every API error, e.g.
 *
 * ```json
 * { "statusCode": 404, "code": "PROJECT_NOT_FOUND", "message": "Project not found" }
 * ```
 *
 * Clients should branch on `code` (a contract) rather than on `message` (copy
 * that is allowed to change).
 */
export const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SOCIAL_ONLY_ACCOUNT: 'SOCIAL_ONLY_ACCOUNT',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  RESET_TOKEN_USED: 'RESET_TOKEN_USED',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
  OAUTH_ACCOUNT_LINKED_ELSEWHERE: 'OAUTH_ACCOUNT_LINKED_ELSEWHERE',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // Resources (404 doubles as "not yours" — see common/authz/ownership.ts)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  SNIPPET_NOT_FOUND: 'SNIPPET_NOT_FOUND',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  IMPORT_JOB_NOT_FOUND: 'IMPORT_JOB_NOT_FOUND',

  // Import pipeline
  GITHUB_NOT_CONNECTED: 'GITHUB_NOT_CONNECTED',
  GITHUB_TOKEN_EXPIRED: 'GITHUB_TOKEN_EXPIRED',
  REPOSITORY_NOT_FOUND: 'REPOSITORY_NOT_FOUND',
  REPOSITORY_EMPTY: 'REPOSITORY_EMPTY',
  REPOSITORY_TOO_LARGE: 'REPOSITORY_TOO_LARGE',
  IMPORT_ALREADY_RUNNING: 'IMPORT_ALREADY_RUNNING',
  IMPORT_TIMEOUT: 'IMPORT_TIMEOUT',
  AI_NOT_CONFIGURED: 'AI_NOT_CONFIGURED',
  AI_FAILED: 'AI_FAILED',

  // Upstream / misc. NOT_FOUND_GENERIC is the fallback for a 404 that carries no
  // resource-specific code (unknown route, row deleted mid-flight, ...).
  GITHUB_API_FAILED: 'GITHUB_API_FAILED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND_GENERIC: 'NOT_FOUND_GENERIC',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
