[build]
builder = "nixpacks"
buildCommand = "cd Backend && npm install && npm run build"

[deploy]
startCommand = "cd Backend && npm run start:prod"
healthcheckPath = "/api/v1/auth/login"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
